name: Build & Push Docker Image

on:
  workflow_run:
    workflows: [ "Run PyTest tests" ]
    types:
      - completed
    branches:
      - main

jobs:
  build-n-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/luiggi33/tibros-scraper:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          github-token: '${{ github.token }}'